

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests



dist: xenial
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

before_script:
  - pip install conan
  - conan remote add conan "https://api.bintray.com/conan/conan/public-conan" ; conan remote add taocpp https://api.bintray.com/conan/taocpp/public-conan
script:
  - export CC=gcc-9
  - export CXX=g++-9
  - mkdir build
  - cd build
  - conan install .. --build=missing --settings compiler.libcxx="libstdc++11"
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
  - make -j
  - ./bin/tests/tests