dist: xenial
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
script:
  - export CC=gcc-9
  - export CXX=g++-9
  - cmake .
  - make
  - ./tests